spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?user=postgres.tqjbkczwtgwcgdrhewko&password=JULIO@cesar1971&sslmode=require
spring.datasource.username=postgres.tqjbkczwtgwcgdrhewko
spring.datasource.password=JULIO@cesar1971
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

jwt.secret=d8f3a9c1e7b24f5aa6c91d3b8e2f4c7a9d1e6b3f0c2a8d9e5f7b1c3a6d8e0f2
jwt.expiration=604800000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

logging.level.com.worldcup=INFO
logging.level.org.springframework.security=WARN

server.port=8080